name: Deploy to GCS

on:
  push:
    branches:
      - main  # Modify this according to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ SECRETS.GCP_WORKLOADIDENTITYPROVIDER }}
        service_account: ${{ SECRETS.GCP_SERVICEACCOUNT }}

    - name: Copy file to GCS bucket
      run: |
        gsutil cp index.html gs://${{ SECRETS.GCP_BUCKET_NAME }} 
