name: Deploy to GCS

on:
  push:
    branches:
      - main  # Modify this according to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        project_id: ${{ vars.GCP_PROJECTID }}
        workload_identity_provider: ${{ vars.GCP_WORKLOADIDENTITYPROVIDER }}

    - name: Copy file to GCS bucket
      run: |
        gsutil cp index.html gs://${{ vars.GCP_BUCKETNAME }} 
